### ISSUE TITLE
Can you teach me how to hack a website??

### ISSUE THREAD

**Issue by roshanfbraju** [brannondorsey/wifi-cracking#11]
I need to hack any off the following websites.. http://plamwallpaper.com , hdwallpaper.in or http://wallpaperlatest.com

**Comment by suadev** [comment]
@roshanfbraju  lol

**Comment by mluis** [comment]
@roshanfbraju that has nothing to do with wifi-cracking :(

**Comment by brannondorsey** [comment]
What you've just asked my help for is a crime. You've also publicly announced your intent to pwn those sites which means if you do, it may be pretty trivial to attribute it to you. Please do not do this, especially if you are inexperienced. You may very likely end up in jail.

**Comment by roshanfbraju** [comment]
Omg!! I really don't know!! 😱 I just wanted similar CSS style. Any way..
thanks for the information. I never even think about it :)

On Jul 27, 2017 8:11 PM, "Brannon Dorsey" <notifications@github.com> wrote:

What you've just asked my help for is a crime. You've also publicly
announced your intent to pwn those sites which means if you do, it may be
pretty trivial to attribute it to you. Please do not do this, especially if
you are inexperienced. You may very likely end up in jail.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/brannondorsey/wifi-cracking/issues/11#issuecomment-318382799>,
or mute the thread

**Comment by mluis** [comment]
@roshanfbraju did you found the Enlightened web just now or what? :)
