### ISSUE TITLE
Follow hashcat recommendations

### ISSUE THREAD

**Issue by enilfodne** [brannondorsey/wifi-cracking#15]
Due to many problems around capturing handshakes, the `hashcat` community recommends using ZerBea's [hcxtools](https://github.com/ZerBea/hcxtools) which simplify and automate the capturing of WPA/WPA2 handshakes. They also reduce the potential problems that many new users might experience otherwise.

`aircrack-ng` is treated as obsolete.

Example usage for capturing handshakes:

```sh
./wlandump-ng -i <wlandevice> -o <output>.cap -c 1 -t 60 -d 100 -D 10 -m 512 -b -r -s 20
```

What this command would do is:

* Start in the 2.4Ghz range from channel 1 (will go to 13)
* stay on a channel for 60s
* send death every 100 beacons
* disassociate every 10 frames

This would produce a `cap` file with multiple handshakes (if there handshakes to be captured) that should be processed by `cap2hccapx` in order to be usable in `hashcat`.

There are also many more utils in that repo that handle edge-cases or simplify a specific use-case.

**Comment by brannondorsey** [comment]
Does that call to `wlandump-ng` attempt to capture handshakes from all APs in the area? Also, is it possible to run `wlandump-ng` without sending deauth packets?

**Comment by enilfodne** [comment]
Yes, you can set `-d 0` which would effectively disable deauth.

**Comment by brannondorsey** [comment]
So yes to the first question too? Is there a way to target a specific AP?

**Comment by enilfodne** [comment]
No, currently there's no way to specify a single ESSID, you can filter it out of the `pcap`, but it will capture a handshake if it sees one.

**Comment by brannondorsey** [comment]
Thats actually a pretty nifty feature for blanket collection. I've been toying around with the idea of adding an appendix to mention alternative methods like this and the suggestion for using [crunch](https://github.com/brannondorsey/wifi-cracking/pull/17). I'll see if I can write something like that this weekend. I'm not going to include this in the main README.md at the moment as it doesn't allow for targeted collection and requires another tool to be installed. Thank you for this :+1: 

I can see myself using `wlandump-ng` more in practice actually.

**Comment by brannondorsey** [comment]
I've included this information in the [new appendix](https://github.com/brannondorsey/wifi-cracking/blob/master/appendix.md). Thank you very much for this contribution :smiley_cat:. `wlandump-ng` is amazing!
