### ISSUE TITLE
clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by abetday** [brannondorsey/wifi-cracking#19]
#15 When I Run:
HASH_FILE=work.hccapx POT_FILE=work.pot HASH_TYPE=2500 ./naive-hashcat.sh

#15 Then this followed:
hashcat (v3.6.0) starting...

clGetPlatformIDs(): CL_PLATFORM_NOT_FOUND_KHR

Started: Sun Jul 30 01:42:29 2017
Stopped: Sun Jul 30 01:42:29 2017

#15 I have try to resolve it but failed . Any suggestions ? Thx.

**Comment by brannondorsey** [comment]
That looks like an OPENCL error thrown inside of Hashcat. What operating system/version are you using?

**Comment by brannondorsey** [comment]
See https://github.com/hashcat/hashcat/issues/1207 and https://hashcat.net/forum/thread-6544.html. One user suggested running hashcat (which is called from inside `naive-hashcat`) with sudo.

**Comment by brannondorsey** [comment]
Closing. Please re-open if need be.

**Comment by anandumdas** [comment]
Intel CPUs require OpenCL Runtime for Intel Core and Intel Xeon Processors (16.1.1 or later). Download and install OpenCL™ Runtime latest from intel website. Ignore the compatibility warning.

Source: https://youtu.be/AieYqNQ6ADM
