### ISSUE TITLE
create a new branch for the Chinese version

### ISSUE THREAD

**Issue by neal1991** [brannondorsey/wifi-cracking#21]
I am interested in your awesome work. And I want to create a new branch to translate this tutorial into Chinese. Will it be allowed?
Thanks.

**Comment by brannondorsey** [comment]
This would be amazing! I will absolutely merge it :+1: How about `README.zh.md` and `appendix.zh.md`?

**Comment by neal1991** [comment]
So I would create the branch named `ch` which will contained the files you mentioned. Will it we OK?

**Comment by brannondorsey** [comment]
That sounds great. And then I will merge your branch into master and link to them from the English version as well. Thank you!

**Comment by brannondorsey** [comment]
Please let me know if I can help you in any way by answering questions etc.

**Comment by neal1991** [comment]
The pr has been proposed, any problem, please tell me directly.

**Comment by brannondorsey** [comment]
Thanks so much for this contribution. I've merged into `master` and linked/offered thanks to you in the README.md. If you would like to include those changes in the Chinese versions I will accept another PR. I greatly appreciate your efforts in this endeavor. It's exciting to have this text translated!
