### ISSUE TITLE
Negative fixed channel

### ISSUE THREAD

**Issue by ArslanAle** [brannondorsey/wifi-cracking#24]
Hi,

For capturing handshake, after running command `airodump-ng -c 52 --bssid DC:9F:DB:30:C1:7A -w . mon0` I see "fixed channel mon0: -1" on the top right corner.

```
 CH 52 ][ Elapsed: 4 s ][ 2017-08-05 13:08 ][ fixed channel mon0: -1 

 BSSID                       PWR RXQ  Beacons    #Data, #/s  CH  MB   ENC  CIPHER AUTH ESSID
                                                                                          
 DC:9F:DB:30:C1:7A  -51       0        5                  0    0      4  54e  WPA2 CCMP   PSK  EasyBox-XXX
                                                                                          
 BSSID              STATION            PWR   Rate    Lost    Frames  Probe
```
`[ WPA handshake: ..` is only displayed (momentarily) if I reconnect to wifi with same machine where I am running this aiodump.

**Comment by brannondorsey** [comment]
From the [Aircrack-ng website](http://aircrack-ng.org/):

> If you are having issues injecting or if you are receiving an error message talking about channel -1 or fixed channel in airodump-ng (top right of the screen) or aireplay-ng, kill the network managers using "airmon-ng check kill" before putting the wireless card in monitor mode.

I would recommend running `airmon-ng check` first to see if it lists any processes that may need to be killed. If so, follow that with `airmon-ng check kill`. If that doesn't work, I've also had luck putting my device into monitor mode manually with:

```
sudo ifconfig wlan0 down
sudo iwconfig wlan0 mode monitor
sudo ifconfig wlan0 up
```

This method puts the device into monitor mode without creating a new `mon0` virtual device, so be sure to use `wlan0` where you would otherwise use `mon0` for all of the tasks in the tutorial.

**Comment by ArslanAle** [comment]
`airmon-ng check kill` worked like a charm. Thanks.

**Comment by kelega** [comment]
I have the same issue but none of solutions worked for me
I used airmon-ng check kill before putting wlan in monitor mode but the problem still remain.
and solution2 give me this error :
```
~# sudo iwconfig wlan0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.
```
any idea?

**Comment by brannondorsey** [comment]
It looks like your device may not support monitor mode. I'd recommend purchasing a compatible USB WiFi dongle from [this list](http://www.wirelesshack.org/best-kali-linux-compatible-usb-adapter-dongles-2016.html).
