### ISSUE TITLE
Chinese translation is confusing

### ISSUE THREAD

**Issue by yizhiheng** [brannondorsey/wifi-cracking#25]
I tried to follow the translated instruction of `README` and `appendix` but I was totally confused by the wording in the documents. They look like a copy/paste from google translate..

Do you accept PRs? If so, I would like to correct some wordings in those docs and make them more readable.

Thanks.

**Comment by brannondorsey** [comment]
Hi @yizhiheng thanks for reaching out :) @neal1991 has been leading the Chinese translation of this document. I can't read or write in Mandarin or Cantonese, so I'm not much of a judge as too what is and is not confusing (sorry about that). Would the two of you be interested in discussing updates? I will definitely accept PRs :+1:

**Comment by brannondorsey** [comment]
My first priority is certainty to include a translation that is easy to understand and helpful to as many readers as possible :smile_cat:

**Comment by yizhiheng** [comment]
@brannondorsey Thanks for the reply.

Cool. I will find some time to work on this later this week, and request a review from @neal1991 !

**Comment by brannondorsey** [comment]
Wonderful. I appreciate the contribution!

**Comment by neal1991** [comment]
@yizhiheng @brannondorsey To be honest, it is really annoying to hear that my translation is copy/paste form google translation. I do have utilized google translation, but not copy/paste. Most of the article is translate myself word by word. It really hurt me for my work. You can access my [translation](https://github.com/neal1991/articles-translator). If I translate this tutorial just by google translation. What is the significance? I am really not so boring to do nonsense.
So, please express your opinion with your responsibility. You have done nothing, and you mustn't to judge other's work with no evidence. If there is something confusing, you can contact me for discussion.

**Comment by brannondorsey** [comment]
Hey @neal1991 and @yizhiheng. First off I want to make it very clear that I am incredibly appreciative to @neal1991 for the work that he has done and the initiative that he has taken in providing this contribution. I am sympathetic to criticism of his work. Unfortunately I am not in a position to edit/read any of the Chinese content submitted as a PR, but I do want to help mitigate any tensions and help facilitate a respectful conversation. @neal1991, thank you again for the work that you have done. @yizhiheng I am indeed open to suggestions and edits but lets make sure that it is done so in a way that is respectful to the work that has already been done.

**Comment by neal1991** [comment]
I welcome specific discussion for the translation. You can point out where is the problem. I will try my best to modify. However, I can never accept irresponsible criticism.

**Comment by yizhiheng** [comment]
@neal1991 I do apologize for what I said above. 😞

I did find some confusions in the translated docs when I tried to follow the steps. As result, I had to read the English docs to figure out.

I'm closing this issue for now and will issue a PR on those docs so that we can have more discussions there.

**Comment by Songkeys** [comment]
@neal1991 Thanks for your hard work. But there are indeed some confusions in the Chinese version.
For example, in the `appendix.zh.md`:
```
...
2. Now you'll need to wait for a device to connect to the target network. If you are testing this on your network (which you should be), reconnect a wireless device to capture a handshake.
...
```
should be translated into:
```
...
现在，你需要等待有一个设备去连接该目标网络。如果你现在正在你自己的网络上测试（按理说应该如此），请用一个无线设备连接以捕获握手。
...
```
to make it clear, I think.

Also, the following step:
```
...
Convert the capture file to .hccapx by uploading it to https://hashcat.net/cap2hccapx/.
...
```
should be:
```
...
将捕获文件上传到 https://hashcat.net/cap2hccapx/ 以转换成 .hccapx 格式。
...
```
Your translation:`将捕获文件转换为.hccapx，将其上传到https://hashcat.net/cap2hccapx/。 ` confused me that I thought it is a two-step stuff.
Thanks for your work anyway, but I think this can be improved a lot. :)

**Comment by brannondorsey** [comment]
Hi @Songkeys, thank you for the suggested edits. Discussion about proposed edits to the Chinese translation has moved to #26. Would you mind proposing these edits there? Cheers :smile_cat:
