### ISSUE TITLE
Reach my hands for Help from God

### ISSUE THREAD

**Issue by abetday** [brannondorsey/wifi-cracking#27]
CH 12 ][ Elapsed: 1 min ][ 2017-08-20 20:25 ][ fixed channel mon0: -1 
....

And I can never get the WPA handshake .
And I can't resove it according the Internet.
And this hurt me .
now ,
I am crying ...
Oh , my God .
Help me, Please . God.

**Comment by brannondorsey** [comment]
Please see #24.
