### ISSUE TITLE
Wireless Card Disclaimer

### ISSUE THREAD

**Issue by 0XE4** [brannondorsey/wifi-cracking#9]
It may be worth noting that V2 of the TL-WN722N uses a chipset that is not compatible with monitoring and therefore not suitable for this process. V1 is still fine. The Alfa AWUS036NHA appears to work with Kali following this guide.

**Comment by brannondorsey** [comment]
Is there a way to check which version you are purchasing on most vendor sites?

**Comment by 0XE4** [comment]
No, sometimes it's on the sticker on the underside of the device itself.

**Comment by brannondorsey** [comment]
I've updated the document to point towards a June 2017 list of supported cards. Thanks for this :+1:
